spring:
    application:
        name: space-spring

server:
    port: 8080
test:
    env: ${TEST_ENV:default_value}
secret:
    jwt-secret-key: "JWT_SECRET_KEY"
    jwt-expired-in: "JWT_EXPIRED_IN"



