
server:
    port: 8080

test:
    env: ${TEST_ENV:default-test-value}


spring:
  datasource:
      url:  ${DATASOURCE_URL_LOCAL}
      username: ${DATASOURCE_USERNAME}
      password: ${DATASOURCE_PASSWORD}
      driver-class-name: ${DATASOURCE_DRIVER}

  jpa:
    hibernate:
          ddl-auto: update          # create : 존재하는 table을 전부 drop했다가 다시 생성 -> 테스트용
    properties:
      hibernate:
        format_sql: true
        show_sql: true

cloud:
  aws:
    credentials:
      access-key: ${S3-ACCESS-KEY}
      secret-key: ${S3-SECRET-KEY}
    s3:
      bucket: project-space-image-storage
    region:
      static: ap-northeast-2 # 리전 정보(서울)
    stack:
      auto: false

secret:
  jwt-secret-key: ${JWT_SECRET_KEY}
  jwt-expired-in: ${JWT_EXPIRED_IN:360000000}

logging:
  level:
    org.hibernate.sql: debug
